### PR TITLE
project list bound to dashboard

### PR DESCRIPTION
**Pull request by Krunal-Promact**
Here in this Pull Request, two task are completed
1) Project list bound to dashboard
2) 404 route added.

Files Changes
1) ProjectRepository.cs - order by clause added.
2) app.module.ts - core module added and 404 related changes
3) app.routes.ts - 404 route related changes
4) http.service.ts - http middle ware 
5) dashboard.module.ts - service injected
6) project-list.component.html - template for project list
7) project-list.component.ts - component responsible for displaying project list
8) project.model.ts - interface for project
9) project.service.ts - project service for database operations
10) notfound.component.ts - Not found component. responsible for 404
11) systemjs.config.js - removed unnecessary comma.

### CODE REVIEW

**Comment by chintans** [comment]
Why are we using systemjs? It is extremely slow. we must use AOT for any application.

**Comment by Krunal-Promact** [comment]
Will implement AOT. Should I also upgrade angular version to 4.0.3?

**Comment by chintans** [comment]
Please upgrade it to 4.0.3

**Comment by Krunal-Promact** [comment]
If there is no issue with this PR then please approve it. I will next take work of AOT and will also update angular in that and will send you different PR.

**Review by chintans — APPROVED** [review]

**Pull request merged**
